##########################################################
##################  所有profile共有的配置  #################
##########################################################

###################  autumn  ###################
#autumn:
#  swagger-open: true #是否开启swagger (true/false)
#  kaptcha-open: false #是否开启登录时验证码 (true/false)
#  session-open: false #是否开启session超时验证（受影响的类SessionTimeoutInterceptor） (true/false)
#  #file-upload-path: d:/tmp  #文件上传目录(不配置的话为java.io.tmpdir目录)
#  muti-datasource-open: false #是否开启多数据源(true/false)
#  spring-session-open: false #是否开启spring session,如果是多机环境需要开启(true/false)
#  session-invalidate-time: 1800 #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
#  session-validation-interval: 900 #多久检测一次失效的session(只在单机环境下生效) 单位：秒

###################  项目启动端口  ###################
server:
  port: 80

###################  spring配置  ###################
spring:
#  profiles:
#    active: dev
  http:
    converters:
      preferred-json-mapper: fastjson
    multipart:
      max-request-size: 100MB #最大请求大小
      max-file-size: 100MB #最大文件大小
#  devtools:
#    restart:
#      enabled: false #是否开启开发者工具（true/false）
#      additional-paths: src/main/java
#      exclude: static/**,WEB-INF/view/**
  aop:
    proxy-target-class: true #false为启用jdk默认动态代理,true为cglib动态代理
  thymeleaf:
    cache: false # 是否开启缓存
    check-template-location: true # 是否检查模板路径是否存在
    content-type: text/html # Contetn-Type的值
    enabled: true # 是否启用Thymeleaf
    encoding: utf-8 # 模板编码
    excluded-view-names:
    mode: LEGACYHTML5
    prefix: classpath:/templates/ # 模板路径
    suffix: .html
    template-resolver-order:
  datasource:
    url: jdbc:mysql://10.10.60.38:3306/autumn?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
#    filters: log4j,wall,mergeStat
  jpa:
    show-sql: true
    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update

##########################################################
###################  开发环境的profile  ###################
##########################################################
#spring:
#  profiles: dev
#  datasource:
#      url: jdbc:mysql://127.0.0.1:3306/autumn?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
#      username: root
#      password:
#      driver-class-name: com.mysql.jdbc.Driver
#      filters: log4j,wall,mergeStat
#
#logging:
#  level.root: info
#  level.com.stylefeng: debug
#  path: logs/
#  file: autumn.log

##########################################################
###################  正式环境的profile  ###################
##########################################################
#spring:
#  profiles: produce
#  datasource:
#      url: jdbc:mysql://127.0.0.1:3306/autumn?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
#      username: root
#      password:
#      driver-class-name: com.mysql.jdbc.Driver
#      filters: log4j,wall,mergeStat
#
#logging:
#  level.root: warn
#  path: logs/
#  file: autumn.log